#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  ./runme.sh build [image-name]
  ./runme.sh restricted [workspace-dir]
  ./runme.sh discovery [workspace-dir]

Commands:
  build       Build the AI sandbox image (reads sandbox.conf, regenerates allowlists)
  restricted  Run the container with the firewall enabled (agent runs as non-root, NET_ADMIN/NET_RAW dropped)
  discovery   Run the container with unrestricted egress and background capture (runs as sandbox user)

Environment variables:
  IMAGE_NAME          Image to use or build (default: ai-sandbox)
  SSH_SCOPE_DIR       Host SSH subdirectory to mount as ~/.ssh (default: ~/.ssh)
  SANDBOX_UID         UID for the container user (default: host user's id -u)
  SANDBOX_GID         GID for the container user (default: host user's id -g)
  SANDBOX_USER        Username for the container user (default: host username from id -un)
  SANDBOX_GROUP       Group name for the container user (default: host primary group from id -gn)
  EXTRA_MOUNTS        Space-separated list of extra host directories to mount under /repos.
                      Append :ro or :rw to control access per directory (default: rw).
                      Examples:
                        EXTRA_MOUNTS="/path/to/repo"              # read-write (default)
                        EXTRA_MOUNTS="/path/to/repo:ro"           # read-only
                        EXTRA_MOUNTS="/path/to/a:ro /path/to/b"  # a=read-only, b=read-write
  SELF_HEALING_ENABLED  Set to 0 to disable self-healing allowlist (default: 1).
                        When disabled, blocked traffic is logged but IPs are never auto-allowed.

Configuration:
  Edit sandbox.conf to enable or disable optional components before building.
EOF
}

# ── Config helpers ─────────────────────────────────────────────────────────────

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
config_file="${script_dir}/sandbox.conf"
image_name="${IMAGE_NAME:-ai-sandbox}"

check_config() {
  if [[ ! -f "$config_file" ]]; then
    printf 'ERROR: sandbox.conf not found in %s\n' "$script_dir" >&2
    exit 1
  fi
}

# Returns 0 if the component is set to ON in sandbox.conf, 1 otherwise.
is_enabled() {
  grep -q "^${1}=ON$" "$config_file" 2>/dev/null
}

# Returns 0 if at least one of the given components is ON.
any_enabled() {
  local c
  for c in "$@"; do
    if is_enabled "$c"; then return 0; fi
  done
  return 1
}

# ── Allowlist generation ────────────────────────────────────────────────────────

# Append a fragment file to stdout; silently skip if the file does not exist.
include_fragment() {
  local fragment="$1"
  if [[ -f "$fragment" ]]; then cat "$fragment"; fi
}

# Append a fragment only when at least one of the listed components is enabled.
include_if_enabled() {
  local fragment="$1"; shift
  if any_enabled "$@"; then
    include_fragment "$fragment"
  fi
}

generate_allowlists() {
  local domains_d="${script_dir}/allowlist-domains.d"
  local proxy_d="${script_dir}/allowlist-proxy-domains.d"
  local cidrs_d="${script_dir}/allowlist-cidrs.d"

  printf 'Generating allowlists from sandbox.conf...\n'

  # allowlist-domains.txt
  {
    printf '# AUTO-GENERATED by runme.sh — do not edit directly.\n'
    printf '# Edit files in allowlist-domains.d/ and run: ./runme.sh build\n\n'
    include_fragment    "$domains_d/base.txt"
    include_if_enabled  "$domains_d/github-cli.txt"      github-cli
    include_if_enabled  "$domains_d/github-copilot.txt"  copilot
    include_if_enabled  "$domains_d/kiro.txt"            kiro
    include_if_enabled  "$domains_d/claude-code.txt"     claude-code
    include_if_enabled  "$domains_d/codex.txt"           codex
    include_if_enabled  "$domains_d/gemini.txt"          gemini
    include_if_enabled  "$domains_d/yarn.txt"            yarn
    include_if_enabled  "$domains_d/kubectl.txt"         kubectl
    include_if_enabled  "$domains_d/aws-cli.txt"         aws-cli
    include_if_enabled  "$domains_d/azure-cli.txt"       azure-cli
    include_if_enabled  "$domains_d/dynatrace.txt"       dtctl dtmgd
    include_if_enabled  "$domains_d/openjdk.txt"         openjdk-21 openjdk-25 graalvm-25
    include_fragment    "$domains_d/custom.txt"
  } > "${script_dir}/allowlist-domains.txt"

  # allowlist-proxy-domains.txt
  {
    printf '# AUTO-GENERATED by runme.sh — do not edit directly.\n'
    printf '# Edit files in allowlist-proxy-domains.d/ and run: ./runme.sh build\n\n'
    include_if_enabled  "$proxy_d/github-copilot.txt"  copilot
    include_if_enabled  "$proxy_d/kiro.txt"            kiro
    include_if_enabled  "$proxy_d/dynatrace.txt"       dtctl dtmgd
    include_fragment    "$proxy_d/custom.txt"
  } > "${script_dir}/allowlist-proxy-domains.txt"

  # allowlist-cidrs.txt
  {
    printf '# AUTO-GENERATED by runme.sh — do not edit directly.\n'
    printf '# Edit files in allowlist-cidrs.d/ and run: ./runme.sh build\n\n'
    include_fragment    "$cidrs_d/base.txt"
    include_if_enabled  "$cidrs_d/github-copilot.txt"  copilot
    include_fragment    "$cidrs_d/custom.txt"
  } > "${script_dir}/allowlist-cidrs.txt"
}

# ── Build-arg generation ───────────────────────────────────────────────────────

# Populate the named array with --build-arg flags derived from sandbox.conf.
build_args_from_config() {
  local -n _args=$1
  local component arg value
  local mappings=(
    "copilot:INSTALL_COPILOT"
    "kiro:INSTALL_KIRO"
    "claude-code:INSTALL_CLAUDE_CODE"
    "codex:INSTALL_CODEX"
    "gemini:INSTALL_GEMINI"
    "openjdk-21:INSTALL_OPENJDK_21"
    "openjdk-25:INSTALL_OPENJDK_25"
    "graalvm-25:INSTALL_GRAALVM_25"
    "kubectl:INSTALL_KUBECTL"
    "aws-cli:INSTALL_AWS_CLI"
    "azure-cli:INSTALL_AZURE_CLI"
    "github-cli:INSTALL_GITHUB_CLI"
    "angular-cli:INSTALL_ANGULAR_CLI"
    "yarn:INSTALL_YARN"
    "dtctl:INSTALL_DTCTL"
    "dtmgd:INSTALL_DTMGD"
  )
  for mapping in "${mappings[@]}"; do
    component="${mapping%%:*}"
    arg="${mapping##*:}"
    if is_enabled "$component"; then value=1; else value=0; fi
    _args+=(--build-arg "${arg}=${value}")
  done
}

# ── Build ──────────────────────────────────────────────────────────────────────

build_image() {
  check_config
  local build_image_name="${1:-$image_name}"
  local build_args=()

  generate_allowlists
  build_args_from_config build_args

  docker build "${build_args[@]}" -t "$build_image_name" "$script_dir"
}

# ── Run ────────────────────────────────────────────────────────────────────────

# Resolve symlinks to their real path; falls back to the original if not found.
# Passing resolved paths to Docker avoids cross-distro symlink resolution issues
# in Rancher Desktop / WSL2 rootless mode (e.g. ~/.aws → /mnt/c/Users/...).
resolve_path() { readlink -f "$1" 2>/dev/null || printf '%s' "$1"; }

# Append bind-mount flags to an array only if the resolved source directory exists.
# Warns and skips silently if the directory is missing — avoids Docker creating
# an empty directory at the mount target instead of mounting real content.
add_mount_if_exists() {
  local -n _flags=$1
  local original_src="$2" dst="$3" opts="${4:-rw}"
  local src
  src="$(resolve_path "$original_src")"
  if [[ -d "$src" ]]; then
    _flags+=(-v "$src:$dst:$opts")
  else
    printf 'WARNING: skipping mount — directory not found: %s\n' "$original_src" >&2
  fi
}

# Same as add_mount_if_exists but for individual files.
add_file_mount_if_exists() {
  local -n _flags=$1
  local original_src="$2" dst="$3" opts="${4:-rw}"
  local src
  src="$(resolve_path "$original_src")"
  if [[ -f "$src" ]]; then
    _flags+=(-v "$src:$dst:$opts")
  fi
}

run_container() {
  check_config
  local mode="$1"
  local workspace_dir
  workspace_dir="$(resolve_path "${2:-$PWD}")"
  local capture_dir_name="${DISCOVERY_CAPTURE_DIR_NAME:-.agent-discovery}"
  local capture_enabled="0"
  local ssh_scope_dir
  ssh_scope_dir="$(resolve_path "${SSH_SCOPE_DIR:-$HOME/.ssh}")"

  if [[ ! -d "$workspace_dir" ]]; then
    printf 'ERROR: workspace directory does not exist: %s\n' "${2:-$PWD}" >&2
    exit 1
  fi

  # NET_ADMIN: required in both modes for iptables setup.
  # NET_RAW: required in both modes — restricted uses it for the background blocked-traffic capture daemon;
  #          discovery uses it for tcpdump. The agent shell has NET_RAW dropped in restricted mode via capsh.
  local capabilities=(--cap-add=NET_ADMIN --cap-add=NET_RAW)

  local sandbox_username="${SANDBOX_USER:-$(id -un)}"
  local dev_home="/home/$sandbox_username"
  if [[ "$mode" == "discovery" ]]; then
    capture_enabled="1"
    mkdir -p "$workspace_dir/$capture_dir_name"
  fi

  # Validate and build EXTRA_MOUNTS flags; abort early if any path is missing.
  local extra_mount_flags=()
  if [[ -n "${EXTRA_MOUNTS:-}" ]]; then
    for entry in $EXTRA_MOUNTS; do
      local dir opt real_dir
      dir="${entry%%:*}"
      opt="${entry##*:}"
      [[ "$opt" == "$dir" ]] && opt="rw"
      real_dir="$(resolve_path "${dir/#\~/$HOME}")"
      if [[ ! -d "$real_dir" ]]; then
        printf 'ERROR: EXTRA_MOUNTS path does not exist: %s\n' "$dir" >&2
        exit 1
      fi
      extra_mount_flags+=(-v "$real_dir:/repos/$(basename "$dir"):$opt")
    done
  fi

  # Mount credential directories for enabled components only.
  local config_mount_flags=()
  add_mount_if_exists config_mount_flags "$ssh_scope_dir" "$dev_home/.ssh" ro

  # ~/.config/gh is shared by github-cli and copilot; mount if either is on.
  if any_enabled github-cli copilot; then
    add_mount_if_exists config_mount_flags "$HOME/.config/gh" "$dev_home/.config/gh"
  fi
  if is_enabled copilot; then
    add_mount_if_exists config_mount_flags "$HOME/.copilot" "$dev_home/.copilot"
  fi
  if is_enabled kiro; then
    add_mount_if_exists config_mount_flags "$HOME/.kiro" "$dev_home/.kiro"
    add_mount_if_exists config_mount_flags "$HOME/.local/share/kiro-cli" "$dev_home/.local/share/kiro-cli"
  fi
  if is_enabled claude-code; then
    add_mount_if_exists      config_mount_flags "$HOME/.claude"      "$dev_home/.claude"
    add_file_mount_if_exists config_mount_flags "$HOME/.claude.json" "$dev_home/.claude.json"
  fi
  if is_enabled codex; then
    add_mount_if_exists config_mount_flags "$HOME/.codex" "$dev_home/.codex"
  fi
  if is_enabled gemini; then
    add_mount_if_exists config_mount_flags "$HOME/.gemini" "$dev_home/.gemini"
  fi
  if is_enabled yarn; then
    add_mount_if_exists config_mount_flags "$HOME/.yarn" "$dev_home/.yarn"
  fi
  if is_enabled aws-cli; then
    add_mount_if_exists config_mount_flags "$HOME/.aws" "$dev_home/.aws"
  fi
  if is_enabled azure-cli; then
    add_mount_if_exists config_mount_flags "$HOME/.azure" "$dev_home/.azure"
  fi
  if is_enabled kubectl; then
    add_mount_if_exists config_mount_flags "$HOME/.kube" "$dev_home/.kube"
  fi
  if is_enabled dtctl; then
    add_mount_if_exists config_mount_flags "$HOME/.config/dtctl" "$dev_home/.config/dtctl"
  fi
  if is_enabled dtmgd; then
    add_mount_if_exists config_mount_flags "$HOME/.config/dtmgd" "$dev_home/.config/dtmgd"
  fi

  docker run -it --rm \
    "${capabilities[@]}" \
    --add-host=host.docker.internal:host-gateway \
    --cpus="4.0" \
    --memory="8g" \
    -e DEV_CONTAINER_MODE="$mode" \
    -e DISCOVERY_CAPTURE_ENABLED="$capture_enabled" \
    -e DISCOVERY_CAPTURE_DIR="/workspace/$capture_dir_name" \
    -e HOST_WORKSPACE_DIR="$workspace_dir" \
    -e IMAGE_NAME="$image_name" \
    -e SANDBOX_UID="${SANDBOX_UID:-$(id -u)}" \
    -e SANDBOX_GID="${SANDBOX_GID:-$(id -g)}" \
    -e SANDBOX_USER="${SANDBOX_USER:-$(id -un)}" \
    -e SANDBOX_GROUP="${SANDBOX_GROUP:-$(id -gn)}" \
    ${SELF_HEALING_ENABLED:+-e SELF_HEALING_ENABLED="$SELF_HEALING_ENABLED"} \
    -v "$workspace_dir:/workspace" \
    "${extra_mount_flags[@]}" \
    "${config_mount_flags[@]}" \
    -w /workspace \
    "$image_name"
}

# ── Entry point ────────────────────────────────────────────────────────────────

command="${1:-restricted}"

case "$command" in
  build)
    build_image "${2:-$image_name}"
    ;;
  restricted|discovery)
    run_container "$command" "${2:-$PWD}"
    ;;
  -h|--help|help)
    usage
    ;;
  *)
    usage >&2
    exit 1
    ;;
esac
